import { cEl, equationMaker, mathCreator, fillPs } from "../scripts/helpers.js"

export default {
    header: cEl("header", [["id", "header"]], ""),
    main: cEl("main", [["id", "main"]], ""),
    footer: cEl("footer", [["id", "footer"]]),
    hDiv: cEl("div", [["id", "hDiv"]]),
    hNav: cEl("nav", [["id", "hNav"]]),
    hOptions: cEl("select", [["id", "hDivSelect"]]),
    selectO1: cEl("option", [["class", "options"], ["value", "o1"]], "Work with 1"),
    selectO2: cEl("option", [["class", "options"], ["value", "o2"]], "Work with 2"),
    selectO3: cEl("option", [["class", "options"], ["value", "o3"]], "Work with 3"),
    selectO4: cEl("option", [["class", "options"], ["value", "o4"]], "Work with 4"),
    selectO5: cEl("option", [["class", "options"], ["value", "o5"]], "Work with 5"),
    selectO6: cEl("option", [["class", "options"], ["value", "o6"]], "Work with 6"),
    selectO7: cEl("option", [["class", "options"], ["value", "o7"]], "Work with 7"),
    selectO8: cEl("option", [["class", "options"], ["value", "o8"]], "Work with 8"),
    selectO9: cEl("option", [["class", "options"], ["value", "o9"]], "Work with 9"),
    selectO10: cEl("option", [["class", "options"], ["value", "o10"]], "Work with 10"),
    selectO11: cEl("option", [["class", "options"], ["value", "o11"]], "Random 1 - 20"),
    selectO12: cEl("option", [["class", "options"], ["value", "o12"]], "Random 1 - 100"),
    selectO13: cEl("option", [["class", "options"], ["value", "o13"]], "Random 1 - 1000"),
    navBut1: cEl("button", [["id", "addition"], ["class", "navButtons"]], "Addition"),
    navBut2: cEl("button", [["id", "subtraction"], ["class", "navButtons"]], "Subtraction"),
    navBut3: cEl("button", [["id", "multiplication"], ["class", "navButtons"]], "Multiplication"),
    navBut4: cEl("button", [["id", "division"], ["class", "navButtons"]], "Division"),
    equationDivs: equationMaker(10, 3),
    checkAns: cEl("button", [["id", "check"]], "Check Answers"),
    mathCreator: mathCreator,
    // randomInt: randomInt,
    // op: op,
    fillPs: fillPs,
}
