import { cEl, equationMaker, mathCreator, fillPs, listener, check, buildPage, clearSheet } from "../scripts/helpers.js"

export default {
    buildPage: buildPage,
    clearSheet: clearSheet,
    header: cEl("header", [["id", "header"]], ""),
    main: cEl("main", [["id", "main"]], ""),
    footer: cEl("footer", [["id", "footer"]]),
    hDiv: cEl("div", [["id", "hDiv"]]),
    hNav: cEl("nav", [["id", "hNav"]]),
    hOptions: cEl("select", [["id", "hDivSelect"]]),
    selectO1: cEl("option", [["class", "options"], ["value", "o1"]], "Work with 1"),
    selectO2: cEl("option", [["class", "options"], ["value", "o2"]], "Work with 2"),
    selectO3: cEl("option", [["class", "options"], ["value", "o3"]], "Work with 3"),
    selectO4: cEl("option", [["class", "options"], ["value", "o4"]], "Work with 4"),
    selectO5: cEl("option", [["class", "options"], ["value", "o5"]], "Work with 5"),
    selectO6: cEl("option", [["class", "options"], ["value", "o6"]], "Work with 6"),
    selectO7: cEl("option", [["class", "options"], ["value", "o7"]], "Work with 7"),
    selectO8: cEl("option", [["class", "options"], ["value", "o8"]], "Work with 8"),
    selectO9: cEl("option", [["class", "options"], ["value", "o9"]], "Work with 9"),
    selectO10: cEl("option", [["class", "options"], ["value", "o10"]], "Work with 10"),
    selectO11: cEl("option", [["class", "options"], ["value", "o11"]], "Random 0 - 20"),
    selectO12: cEl("option", [["class", "options"], ["value", "o12"]], "Random 0 - 100"),
    selectO13: cEl("option", [["class", "options"], ["value", "o13"]], "Random 0 - 1000"),
    navBut1: cEl("button", [["id", "addition"], ["class", "navButtons"]], "Addition"),
    navBut2: cEl("button", [["id", "subtraction"], ["class", "navButtons"]], "Subtraction"),
    navBut3: cEl("button", [["id", "multiplication"], ["class", "navButtons"]], "Multiplication"),
    navBut4: cEl("button", [["id", "division"], ["class", "navButtons"]], "Division"),
    equationDivs: equationMaker,
    checkAns: cEl("button", [["id", "check"]], "Check Answers"),
    mathCreator: mathCreator,
    fillPs: fillPs,
    check: check,
    listener: listener,
    addObj: {
        o1: (operation) => mathCreator(1, operation),
        o2: (operation) => mathCreator(2, operation),
        o3: (operation) => mathCreator(3, operation),
        o4: (operation) => mathCreator(4, operation),
        o5: (operation) => mathCreator(5, operation),
        o6: (operation) => mathCreator(6, operation),
        o7: (operation) => mathCreator(7, operation),
        o8: (operation) => mathCreator(8, operation),
        o9: (operation) => mathCreator(9, operation),
        o10: (operation) => mathCreator(10, operation),
        o11: (operation) => mathCreator(20, operation),
        o12: (operation) => mathCreator(100, operation),
        o13: (operation) => mathCreator(1000, operation)
    }
}
